language: go

go:
  - 1.10.x


env:
  - TRAVIS=1 PYTHONWARNINGS=ignore

services:
  - mysql
  - mongodb
  - redis-server

before_install:
  - DEP_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
  - DEP_LATEST_RELEASE_URL="https://github.com/golang/dep/releases/download/v0.3.2/dep-${DEP_OS_ARCH}"
  - wget ${DEP_LATEST_RELEASE_URL} -O /tmp/dep
  - export PATH=$PATH:/tmp/
  - chmod +x /tmp/dep
  - mysql -e 'CREATE DATABASE goworld;'
  - curl -L  https://github.com/coreos/etcd/releases/download/v3.3.6/etcd-v3.3.6-linux-amd64.tar.gz -o /tmp/etcd-v3.3.6-linux-amd64.tar.gz
  - tar xzvf /tmp/etcd-v3.3.6-linux-amd64.tar.gz -C /tmp
  - /tmp/etcd-v3.3.6-linux-amd64/etcd &

install:
  - dep ensure
  - make

script:
  - cp goworld.ini.sample goworld.ini
  - make test
  - bash covertest.sh
  - goworld build examples/test_game
  - goworld start examples/test_game
  - sleep 1
  - goworld reload examples/test_game
  - sleep 1
  - goworld stop examples/test_game

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 02233e4f-bf07-4d72-8023-8a47d27cc48b
