language: go

go:
  - 1.8.x


env:
  - TRAVIS=1 PYTHONWARNINGS=ignore

services:
  - mysql
  - mongodb
  - redis-server

before_install:
  - DEP_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
  - DEP_LATEST_RELEASE_URL="https://github.com/golang/dep/releases/download/v0.3.2/dep-${DEP_OS_ARCH}"
  - wget ${DEP_LATEST_RELEASE_URL} -O /tmp/dep
  - export PATH=$PATH:/tmp/
  - chmod +x /tmp/dep

  - mysql -e 'CREATE DATABASE goworld;'

install:
  - dep ensure
  - go install ./cmd/goworld

script:
  - cp goworld.ini.sample goworld.ini
  - make
  - make test
  - bash covertest.sh
  - goworld build examples/test_game
  - goworld start examples/test_game
  - sleep 1
  - goworld reload examples/test_game
  - sleep 1
  - goworld stop examples/test_game

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 02233e4f-bf07-4d72-8023-8a47d27cc48b
