
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  name = "github.com/bmizerany/assert"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.1.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.28.2"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/google/btree"

[[constraint]]
  name = "github.com/natefinch/lumberjack"
  version = "2.1.0"

[[constraint]]
  name = "github.com/pierrec/lz4"
  version = "1.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  source = "https://github.com/xiaonanln/msgpack.git"
  version = "3.0.0"

[[constraint]]
  name = "github.com/xiaonanln/go-trie-tst"

[[constraint]]
  name = "github.com/xiaonanln/go-xnsyncutil"
  version = "0.0.2"

[[constraint]]
  name = "github.com/xiaonanln/goTimer"
  version = "0.0.2"

[[constraint]]
  name = "github.com/xiaonanln/typeconv"
  version = "0.0.2"

[[constraint]]
  name = "github.com/xtaci/kcp-go"
  version = "3.19.0"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "master"
  name = "github.com/keybase/go-ps"
